### ISSUE TITLE
wondering how to accelerate the process of UVMAP2MESH

### ISSUE THREAD

**Issue by super3kl** [reshow/PRNet-PyTorch#15]
cause i want to put the rendering part into the training process,but the rendering process ,especially 'uv2mesh' process takes lots of time. I'll appreciate it if you give me some advice.

**Comment by reshow** [comment]
The mesh triangles are calculated repeatedly in the functiona, but it is the same for all the meshes. You can pre-compute it and save the result. I think it would be much faster.

**Comment by super3kl** [comment]
hello and i got some other new questions:
1: have you ever reproducted the papaer's results like mean NME 3.62 ,but i trained your baseline a lot and got around 3.8 NME according the yaw angle.
2: why does gt_pos in dataerloader have to divide by 280, don't know why it goes with 280 as i compute the gt_pos ,and the range is about[-58,312] for 300W-LP,so i am confused about the normalization
3.i would like add your wechat for details communicatio，or just emails chat is fine .here is my e-mail qianqiubiu@163.com

**Comment by reshow** [comment]
1. I have not calculate the mean NME of prnet.
2. Sorry I forget why I choosed 280😂.
3. rzy503099765@qq.com.

**Comment by rakacendekia** [comment]
> hello and i got some other new questions:
> 1: have you ever reproducted the papaer's results like mean NME 3.62 ,but i trained your baseline a lot and got around 3.8 NME according the yaw angle.
> 2: why does gt_pos in dataerloader have to divide by 280, don't know why it goes with 280 as i compute the gt_pos ,and the range is about[-58,312] for 300W-LP,so i am confused about the normalization
> 3.i would like add your wechat for details communicatio，or just emails chat is fine .here is my e-mail [qianqiubiu@163.com](mailto:qianqiubiu@163.com)

Hello, i got some questions. How is the method to get the mean NME, whether by grouping the database based on its angle, or how?
