### ISSUE TITLE
如何计算3d关键点nem？

### ISSUE THREAD

**Issue by mjanddy** [reshow/PRNet-PyTorch#2]
我在计算3d关键点nem遇到了一些困难，你能提供一份代码吗？

**Comment by reshow** [comment]
你可以参考loss.py中的内容，getError Function('landmark3d')应该是你需要的内容

**Comment by mjanddy** [comment]
那这个gt指的是测试数据集转换成的uv位置图吗？

**Comment by reshow** [comment]
> 那这个gt指的是测试数据集转换成的uv位置图吗？



> 那这个gt指的是测试数据集转换成的uv位置图吗？

指的是在crop之前的图里计算，会有一些浮点误差，0.1％左右

**Comment by mjanddy** [comment]
那如果在crop之前如何获得gt关键点所在呢？
