### ISSUE TITLE
关于关键点的nme测试

### ISSUE THREAD

**Issue by mjanddy** [reshow/PRNet-PyTorch#3]
你好，我想问一下，你的loss.py中 getErrorFunction(error_func_name='NME')函数 中error_func_name的六个参数分别是什么含义？因为得到的结果是 nme2d 要好于landmark2d
![image](https://user-images.githubusercontent.com/27938658/69393785-1cfc6a00-0d15-11ea-95b8-1443416fd6d6.png)

**Comment by reshow** [comment]
The nme2d is calculated from 45K points and the landmark2d is calculated from 68 points (consistent with the paper)

**Comment by mjanddy** [comment]
那gtlandmark2d代表的是所有的points吗？

**Comment by mjanddy** [comment]
![image](https://user-images.githubusercontent.com/27938658/69394112-fc80df80-0d15-11ea-9516-7242b1c6a635.png)
你这个结果中的landmarks和all points 分别是对应你函数中参数哪个？landmark2d和gtlandmark2d吗？

**Comment by reshow** [comment]
Landmark2d is calculated in the cropped image coordinates. Gtlandmark2d is in the raw image.

**Comment by reshow** [comment]
These results are out of date. Just ignore them.

**Comment by mjanddy** [comment]
能提供一下你最新的结果吗？

**Comment by reshow** [comment]
landmark2d:3.20  3d:4.67
nme2d: 3.11  3D 4.33

**Comment by mjanddy** [comment]
好的，多谢了

**Comment by mjanddy** [comment]
按照你的代码训练，如果不修改的话可以得到这个结果吗？

**Comment by reshow** [comment]
I'm not sure. You may need to do more data augmentation and parameter adjustment.

**Comment by mjanddy** [comment]
好的，我去尝试一下，多谢了

**Comment by vitahsu** [comment]
請問這些測試都必須得在GPU的環境下進行嗎?

**Comment by vitahsu** [comment]
@mjanddy 可以請問一下這樣train一次大約耗費多久時間嗎? 謝謝!

**Comment by mjanddy** [comment]
> @mjanddy 可以請問一下這樣train一次大約耗費多久時間嗎? 謝謝!

大概半小时一次

**Comment by vitahsu** [comment]
@mjanddy  請問您在跑的時候有遇到這個問題嗎?

Traceback (most recent call last):
  File "E:/PRNet-PyTorch-master/visualize.py", line 4, in <module>
    from faceutil import mesh
  File "E:\PRNet-PyTorch-master\faceutil\mesh\__init__.py", line 1, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'faceutil.mesh.cython' (unknown location)

是因為我不是在GPU的環境底下run嗎?
謝謝

**Comment by mjanddy** [comment]
> @mjanddy 請問您在跑的時候有遇到這個問題嗎?
> 
> Traceback (most recent call last):
> File "E:/PRNet-PyTorch-master/visualize.py", line 4, in 
> from faceutil import mesh
> File "E:\PRNet-PyTorch-master\faceutil\mesh__init__.py", line 1, in 
> from .cython import mesh_core_cython
> ImportError: cannot import name 'mesh_core_cython' from 'faceutil.mesh.cython' (unknown location)
> 
> 是因為我不是在GPU的環境底下run嗎?
> 謝謝

我没有遇到过这个问题，看起来像是mesh_core_cython这个没有找到，是不是你没有编译

**Comment by reshow** [comment]
> 
> 
> @mjanddy 請問您在跑的時候有遇到這個問題嗎?
> 
> Traceback (most recent call last):
> File "E:/PRNet-PyTorch-master/visualize.py", line 4, in
> from faceutil import mesh
> File "E:\PRNet-PyTorch-master\faceutil\mesh__init__.py", line 1, in
> from .cython import mesh_core_cython
> ImportError: cannot import name 'mesh_core_cython' from 'faceutil.mesh.cython' (unknown location)
> 
> 是因為我不是在GPU的環境底下run嗎?
> 謝謝

You need to follow the instructions of face3d (as explained in README) to compile the cython package. 
I haven't implement the CPU version. But I think you can run it on CPU by deleting some codes look like *.to(*.device)

**Comment by vitahsu** [comment]
@reshow @mjanddy yes! i got it. Thank you! But, when I compile it, it shows another wrong:

(base) E:\PRNet-PyTorch-master\faceutil\mesh\cython>python setup.py build_ext -i
running build_ext
skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
building 'mesh_core_cython' extension
error: Unable to find vcvarsall.bat

Is because of the different version of python? Or other errors?
Thanks!

**Comment by reshow** [comment]
> @reshow @mjanddy yes! i got it. Thank you! But, when I compile it, it shows another wrong:
> 
> (base) E:\PRNet-PyTorch-master\faceutil\mesh\cython>python setup.py build_ext -i
> running build_ext
> skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
> building 'mesh_core_cython' extension
> error: Unable to find vcvarsall.bat
> 
> Is because of the different version of python? Or other errors?
> Thanks!

I have never met such an error. I think you may try to install cython and libpython

**Comment by vitahsu** [comment]
@reshow I try to install python packages showed on website PRNet and now it shows error:

(base) E:\PRNet-PyTorch-master\faceutil\mesh\cython>python setup.py build_ext -i
running build_ext
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    include_dirs=[numpy.get_include()])],
  File "C:\Users\Vita\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Vita\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Vita\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Vita\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\Vita\Anaconda3\lib\distutils\command\build_ext.py", line 309, in run
    force=self.force)
  File "C:\Users\Vita\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Users\Vita\Anaconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Users\Vita\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
    if self.ld_version >= "2.10.90":
TypeError: '>=' not supported between instances of 'NoneType' and 'str'

I try to find error online, but i cannot deal with it ><. My python version is 3.7.3 and VS15.
I have checked the environment setting VS140COMNTOOLS C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\.
Do you have any idea?
Sorry to bother you!
Thank you ><
